# Generated by Django 3.1 on 2023-02-19 00:00

from django.db import migrations, models
import todo.models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='img',
            field=models.ImageField(blank=True, default='media/default.png', null=True, upload_to=todo.models.upload_avatar_path, verbose_name='画像'),
        ),
    ]
