# Generated by Django 3.1 on 2023-02-19 01:40

from django.db import migrations, models
import todo.models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20230219_0000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='img',
            field=models.ImageField(blank=True, default='media/avatars/default.png', null=True, upload_to=todo.models.upload_avatar_path, verbose_name='画像'),
        ),
    ]
