# Generated by Django 3.1 on 2023-02-20 19:35

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import todo.models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_auto_20230219_0140'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='access',
            field=models.CharField(choices=[('1', 'public'), ('2', 'private')], default='1', max_length=40),
        ),
        migrations.AddField(
            model_name='task',
            name='estimate',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.CreateModel(
            name='SubTask',
            fields=[
                ('id', models.CharField(default=todo.models.uuid4, editable=False, max_length=33, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=50, verbose_name='タイトル')),
                ('description', models.TextField(blank=True, max_length=1000, null=True, verbose_name='概要')),
                ('status', models.CharField(choices=[('1', 'Not started'), ('2', 'On going'), ('3', 'Done')], default='1', max_length=40)),
                ('access', models.CharField(choices=[('1', 'public'), ('2', 'private')], default='1', max_length=40)),
                ('estimate', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('subTaskInTask', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subTaskInTask', to='todo.task')),
                ('subTaskOwner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subTaskOwner', to=settings.AUTH_USER_MODEL)),
                ('subTaskResponsible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subTaskResponsible', to=settings.AUTH_USER_MODEL)),
                ('userSubTask', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userSubTask', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('taskGroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taskGroup', to='todo.task')),
                ('userGroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userGroup', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
